import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import { sanityClient, urlFor } from "../sanity";
import Link from "next/link";

interface Post {
  _id: string;
  _createdAt: string;
  title: string;
  author: {
    name: string;
    image: string;
  };
  description: string;
  mainImage: {
    asset: {
      url: string;
      _ref: string;
    };
  };
  slug: {
    current: string;
  };
  body: object[];
}

interface Props {
  posts: Post[];
}

export default function Home({ posts }: Props) {
  return (
    <div className="mx-auto max-w-7xl">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <div className="flex items-center justify-between py-10 bg-yellow-400 border-black border-y lg:py-0">
        <div className="px-10 py-4 space-y-5">
          <h1 className="max-w-xl font-serif text-6xl ">
            <span className="underline decoration-black decoration-4">
              Medium {""}
            </span>
            is a place to write, read and connect
          </h1>
          <h2 className="">
            Discover stories, thinking, and expertise from writers on any topic.
          </h2>
        </div>

        <img
          className="hidden h-32 pr-6 md:inline-flex lg:h-40 "
          src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Medium_icon.svg/2560px-Medium_icon.svg.png"
          alt="inital logo"
        />
      </div>
      <div className="grid grid-cols-1 gap-3 p-2 sm:grid-cols-2 lg:grid-cols-3 md:gap-6 md:p-6">
        {posts.map((post) => {
          return (
            <Link key={post._id} href={`/post/${post.slug.current}`}>
              <div className="overflow-hidden border rounded-lg cursor-pointer group">
                <img
                  className="object-cover w-full transition-transform duration-200 ease-in-out h-60 group-hover:scale-105"
                  src={urlFor(post.mainImage).url()!}
                  alt="main image"
                />
                <div className="flex justify-between p-5 bg-white ">
                  <div>
                    <p className="text-lg font-bold">{post.title}</p>
                    <p className="text-xs">
                      {post.description} by {post.author.name}{" "}
                    </p>
                  </div>
                  <img
                    className="w-12 h-12 rounded-full"
                    src={urlFor(post.author.image).url()!}
                    alt="avatar"
                  />
                </div>
              </div>
            </Link>
          );
        })}
      </div>
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = `
  *[_type =="post"] {
    _id,
    title,
    description,
    mainImage,
    slug,
    author -> {
    name,
    image 
  }
  }`;

  const posts = await sanityClient.fetch(query);

  return {
    props: {
      posts,
    },
  };
};
